### ISSUE TITLE
@Named annotation missing in InstrumentedNioEventLoopGroupFactory

### ISSUE THREAD

**Issue by alvarogl** [micronaut-projects/micronaut-micrometer#1058]
### Expected Behavior

When `micronaut-micrometer` is used in the project, it replaces Netty `NioEventLoopGroupFactory` with `InstrumentedNioEventLoopGroupFactory`. So the registered `eventLoopGroupFactories` in `DefaultEventLoopGroupFactory`  is a map with the pairs:

- `nio`: `InstrumentedNioEventLoopGroupFactory`
- `epoll`: `EpollEventLoopGroupFactory`
- `native`: `InstrumentedEpollEventLoopGroupFactory` 

Those starting with `Instrumented...` come from `micronaut-micrometer`

If I choose `nio` as the transport mode for my `event-loops`, it should initialize correctly.

### Actual Behaviour

When `DefaultEventLoopGroupFactory`  is  filled with current declarations, a map with the pairs is generated:

- `instrumentedNioEventLoopGroupFactory`: `InstrumentedNioEventLoopGroupFactory`
- `epoll`: `EpollEventLoopGroupFactory`
- `native`: `InstrumentedEpollEventLoopGroupFactory` 

This makes that `nio` is no longer present because the annotation `@Named(NioEventLoopGroupFactory.NAME)` is missing in `InstrumentedNioEventLoopGroupFactory`, leading to an inconsistence declaring the factory methods.

The error thrown:

> Message: No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory, epoll, native]
Path Taken:
@i.m.c.a.EachBean i.n.c.EventLoopGroup i.m.h.n.c.DefaultEventLoopGroupRegistry.eventLoopGroup#eventLoopGroup(EventLoopGroupConfiguration configuration)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2045)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:323)
	at io.micronaut.context.DefaultBeanContext.configureAndStartContext(DefaultBeanContext.java:3362)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:345)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:225)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at micronaut.proxy.Application.main(Application.java:11)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.netty.channel.EventLoopGroup]

To solve this, adding the annotation is required.

### Version

5.13.1

**Comment by sdelamo** [comment]
Steps to reproduce: 

- [Generate a Micronaut app](https://launch.micronaut.io). 
- add dependency: `implementation("io.micronaut.micrometer:micronaut-micrometer-core")`
- add configuration `micronaut.metrics.binders.netty.queues.enabled=true`

Run tests and you will see: 

```

Error instantiating bean of type  [io.netty.channel.EventLoopGroup]

Message: No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory]
Path Taken:
@i.m.c.a.Primary @j.i.Singleton i.n.c.EventLoopGroup i.m.h.n.c.DefaultEventLoopGroupRegistry.defaultEventLoopGroup#defaultEventLoopGroup(@Named("netty") ThreadFactory threadFactory)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.netty.channel.EventLoopGroup]

Message: No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory]
Path Taken:
@i.m.c.a.Primary @j.i.Singleton i.n.c.EventLoopGroup i.m.h.n.c.DefaultEventLoopGroupRegistry.defaultEventLoopGroup#defaultEventLoopGroup(@Named("netty") ThreadFactory threadFactory)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2357)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3162)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:3012)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2774)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1849)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1824)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:863)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:410)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.getEventLoopGroup(DefaultEventLoopGroupRegistry.java:194)
	at io.micronaut.http.server.netty.NettyHttpServer.createWorkerEventLoopGroup(NettyHttpServer.java:525)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:132)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:367)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:86)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.util.NoSuchElementException: No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory]
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.lambda$getFactory$1(DefaultEventLoopGroupFactory.java:174)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.getFactory(DefaultEventLoopGroupFactory.java:174)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.createIoHandlerFactory(DefaultEventLoopGroupFactory.java:124)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.createGroup(DefaultEventLoopGroupRegistry.java:111)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.defaultEventLoopGroup(DefaultEventLoopGroupRegistry.java:181)
	at io.micronaut.http.netty.channel.$DefaultEventLoopGroupRegistry$DefaultEventLoopGroup1$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2342)
	... 15 more


No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory]
java.util.NoSuchElementException: No matching transport was found. Configured transports are [nio], available transports are [instrumentedNioEventLoopGroupFactory]
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.lambda$getFactory$1(DefaultEventLoopGroupFactory.java:174)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.getFactory(DefaultEventLoopGroupFactory.java:174)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.createIoHandlerFactory(DefaultEventLoopGroupFactory.java:124)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.createGroup(DefaultEventLoopGroupRegistry.java:111)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.defaultEventLoopGroup(DefaultEventLoopGroupRegistry.java:181)
	at io.micronaut.http.netty.channel.$DefaultEventLoopGroupRegistry$DefaultEventLoopGroup1$Definition.instantiate(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2342)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3162)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:3012)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2774)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1849)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1824)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:863)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:410)
	at io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry.getEventLoopGroup(DefaultEventLoopGroupRegistry.java:194)
	at io.micronaut.http.server.netty.NettyHttpServer.createWorkerEventLoopGroup(NettyHttpServer.java:525)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:298)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:132)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:367)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:86)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


```

**Comment by sdelamo** [comment]
I assume this is fixed by https://github.com/micronaut-projects/micronaut-micrometer/pull/1051

**Comment by loicmathieu** [comment]
This is still broken on the `6.0.x` line — I hit the exact same `NoSuchElementException: No matching transport was found` migrating [Kestra](https://github.com/kestra-io/kestra) to Micronaut 5, with `micronaut-micrometer-core:6.0.2` (released 2026-08-28, the current latest 6.x release, pulled in transitively via `micronaut-platform:5.1.5`).

I dug into why: #1051 fixed this by rewriting the netty-queue-metrics binder around `TaskQueueInterceptor` and deleting `InstrumentedNioEventLoopGroupFactory`/`InstrumentedEpollEventLoopGroupFactory`/`InstrumentedKQueueEventLoopGroupFactory` entirely — but that PR's base branch was `5.13.x`, not the `6.0.x`/main line. I extracted the `micronaut-micrometer-core-6.0.2-sources.jar` directly and `InstrumentedNioEventLoopGroupFactory.java` is still there, unchanged, still missing the `@Named(NioEventLoopGroupFactory.NAME)` qualifier that its siblings (`InstrumentedEpollEventLoopGroupFactory`, `InstrumentedKQueueEventLoopGroupFactory`) both explicitly redeclare on their own `@Replaces` bean:

```java
@Replaces(bean = EpollEventLoopGroupFactory.class, named = EventLoopGroupFactory.NATIVE)
@Named(EventLoopGroupFactory.NATIVE)
final class InstrumentedEpollEventLoopGroupFactory extends EpollEventLoopGroupFactory { ... }
```

vs.

```java
@Replaces(bean = NioEventLoopGroupFactory.class)
// no @Named here
final class InstrumentedNioEventLoopGroupFactory extends NioEventLoopGroupFactory { ... }
```

So the fix from #1051 apparently never made it onto the `6.0.x` release line, and it's currently the only line compatible with Micronaut core/platform 5.x. Anyone on Micronaut 5 who sets `micronaut.metrics.binders.netty.queues.enabled: true` still hits a hard startup failure. Could this be backported/re-released on 6.0.x, or is 6.0.x expected to pick it up from a different branch? Happy to send a PR mirroring #1051's change onto `6.0.x` if that's the right fix.
